# Generated by Django 5.0.2 on 2024-07-19 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qutbeez', '0004_alter_men_options_alter_women_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottomwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottomwear', models.CharField(choices=[('Jeans', 'JEANS'), ('Shorts', 'SHORTS'), ('Formal Trousers', 'FORMAL TROUSERS'), ('Casual Trousers', 'CASUAL TROUSERS'), ('Track Pants & Joggers', 'Track Pants & Joggers')], default='Not available', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('footwear', models.CharField(choices=[('Casual Shoes', 'Casual Shoes'), ('Sports Shoes', 'Sports Shoes'), ('Formal Shoes', 'Formal Shoes'), ('Sneakers', 'Sneakers'), ('Sandals & Floaters', 'Sandals & Floaters'), ('Socks', 'Socks')], default='Not available', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Innerwear_Sleepwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innerwear_sleepwear', models.CharField(choices=[('Boxers', 'Boxers'), ('Vests', 'Vests'), ('Sleepwear & Loungewear', 'Sleepwear & Loungewear'), ('Thermals', 'Thermals')], default='Not available', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sports_Activewear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_activewear', models.CharField(choices=[('Sports Shoes', 'Sports Shoes'), ('Sports Sandals', 'Sports Sandals'), ('Active T-Shirts', 'Active T-Shirts'), ('Track Pants & Shorts', 'Track Pants & Shorts'), ('Tracksuits', 'Tracksuits'), ('Swimwear', 'Swimwear')], default='Not available', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Topwear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topwear', models.CharField(choices=[('T-shirts', 'T-SHIRTS'), ('Casual shirts', 'CASUAL SHIRTS'), ('Jackets', 'JACKETS'), ('Suits', 'SUITS'), ('Sweaters', 'SWEATERS')], default='Not available', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='men_category',
        ),
        migrations.RemoveField(
            model_name='women',
            name='name',
        ),
        migrations.RemoveField(
            model_name='product',
            name='women_category',
        ),
        migrations.AddField(
            model_name='category',
            name='bottomwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qutbeez.bottomwear'),
        ),
        migrations.AddField(
            model_name='category',
            name='footwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qutbeez.footwear'),
        ),
        migrations.AddField(
            model_name='category',
            name='innerwear_sleepwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qutbeez.innerwear_sleepwear'),
        ),
        migrations.AddField(
            model_name='category',
            name='sports_activewear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qutbeez.sports_activewear'),
        ),
        migrations.AddField(
            model_name='category',
            name='topwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qutbeez.topwear'),
        ),
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
