# Generated by Django 5.0.2 on 2024-07-19 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qutbeez', '0005_bottomwear_footwear_innerwear_sleepwear_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottomwear',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='footwear',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='innerwear_sleepwear',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='sports_activewear',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10),
        ),
        migrations.AddField(
            model_name='topwear',
            name='category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'Kids')], default='Men', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='bottomwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='qutbeez.bottomwear'),
        ),
        migrations.AlterField(
            model_name='category',
            name='footwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='qutbeez.footwear'),
        ),
        migrations.AlterField(
            model_name='category',
            name='innerwear_sleepwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='qutbeez.innerwear_sleepwear'),
        ),
        migrations.AlterField(
            model_name='category',
            name='sports_activewear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='qutbeez.sports_activewear'),
        ),
        migrations.AlterField(
            model_name='category',
            name='topwear',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='qutbeez.topwear'),
        ),
    ]
